# Generated by Django 4.2.7 on 2024-04-25 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Settings', models.CharField(max_length=120, unique=True, verbose_name='设置项名')),
                ('value', models.CharField(max_length=4096, verbose_name='值')),
                ('lastModifiedTime', models.DateTimeField(auto_now=True, null=True, verbose_name='上次修改时间')),
                ('lastModifiedUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
            ],
        ),
    ]
